//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumId { get; set; }
        public string AlbumName { get; set; }
        public string ArtistName { get; set; }
        public string Label { get; set; }
        public string Genre { get; set; }
        public Nullable<short> Year { get; set; }
        public string Artwork { get; set; }
    }
}
